export { KYAClient } from "./client.js";
export { KYAError, KYAErrorCode } from "./errors.js";
export { createTrustGate, expressGate, honoGate } from "./middleware.js";
export type {
  AddPresenceParams,
  AddPresenceResponse,
  AddressPresence,
  AgentIdentity,
  AgentProfile,
  AgentSummary,
  Attestation,
  AttestationsResponse,
  BuildFeedbackTxParams,
  BuildFeedbackTxResponse,
  ChainReputation,
  CreateWebhookParams,
  FeedbackChain,
  FeedbackChainsResponse,
  FeedbackComment,
  FeedbackResponse,
  HealthResponse,
  KYAClientConfig,
  LinkAgentsParams,
  LinkAgentsResponse,
  LinkInfo,
  LinksResponse,
  ListAgentsParams,
  Pagination,
  PaginationParams,
  PresenceResponse,
  RemovePresenceParams,
  RemovePresenceResponse,
  ReputationHistoryParams,
  ReputationHistoryResponse,
  ReputationResponse,
  ReputationSnapshot,
  StatsParams,
  StatsResponse,
  SubmitFeedbackParams,
  SubmitFeedbackResponse,
  TrustCheckOptions,
  TrustCheckResult,
  TrustGateOptions,
  UnifiedReputation,
  UnlinkAgentsParams,
  UnlinkAgentsResponse,
  UpdateFeedbackTxResponse,
  UpdateWebhookParams,
  WebhookDeleteResponse,
  WebhookDeliveriesResponse,
  WebhookDelivery,
  WebhookEventType,
  WebhookListResponse,
  WebhookResponse,
} from "./types.js";
