import Database from "better-sqlite3";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Configuration
const DB_FILE = path.join(process.cwd(), "kya.db");
const OUTPUT_FILE = path.join(process.cwd(), "../api/d1_import.sql");

// Order matters for foreign keys
const TABLES = [
    "agents",
    "agent_identities",
    "reputation_latest",
    "reputation_snapshots",
    "sati_attestations",
    "evm_links",
    "wallet_links",
    // sync_cursors is usually specific to the runtime (relayer vs api), but good for debugging
    "sync_cursors"
];

function toSqlValue(v: any): string {
    if (v === null || v === undefined) return "NULL";
    if (typeof v === "number" || typeof v === "bigint") return v.toString();
    if (Buffer.isBuffer(v)) return `x'${v.toString("hex")}'`;
    if (typeof v === "string") return `'${v.replace(/'/g, "''")}'`;
    // Fallback for objects/arrays -> JSON string? No, SQLite typically stores primitives
    return `'${String(v).replace(/'/g, "''")}'`;
}

function main() {
    console.log(`Source DB: ${DB_FILE}`);
    console.log(`Output SQL: ${OUTPUT_FILE}`);

    if (!fs.existsSync(DB_FILE)) {
        console.error("Error: kya.db not found in current directory.");
        process.exit(1);
    }

    // Ensure output dir exists
    const outDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
    }

    const db = new Database(DB_FILE, { readonly: true });

    // Start SQL file
    fs.writeFileSync(OUTPUT_FILE, "-- D1 Import generated by export-d1.ts\nPRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n");

    let totalRows = 0;

    for (const table of TABLES) {
        try {
            const rows = db.prepare(`SELECT * FROM ${table}`).all();
            if (rows.length === 0) continue;

            console.log(`Exporting ${rows.length} rows from ${table}...`);

            for (const row of rows) {
                const cols = Object.keys(row);
                // exclude better-sqlite3's internal props if any

                const vals = cols.map(c => toSqlValue((row as any)[c]));

                const sql = `INSERT OR REPLACE INTO ${table} (${cols.join(", ")}) VALUES (${vals.join(", ")});\n`;
                fs.appendFileSync(OUTPUT_FILE, sql);
            }

            totalRows += rows.length;
        } catch (err: any) {
            if (err.message.includes("no such table")) {
                console.warn(`Table ${table} not found, skipping.`);
            } else {
                throw err;
            }
        }
    }

    fs.appendFileSync(OUTPUT_FILE, "COMMIT;\n");
    console.log(`\nSuccess! Exported ${totalRows} rows to ${OUTPUT_FILE}`);
}

main();
